@ParametersAreNonnullByDefault
@FieldsAndMethodsAreNonnullByDefault
package com.ultramega.interdimensionalwirelesstransmitter.neoforge.datagen.loot;

import com.refinedmods.refinedstorage.api.core.FieldsAndMethodsAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
